[phases.setup]
nixPkgs = ["python311", "gcc", "libGL", "glib", "libsndfile", "poppler_utils", "tesseract"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "uvicorn api:app --host 0.0.0.0 --port $PORT"
